sudo: required
services: docker

branches:
  only:
  - native

script:
  - docker run --rm --privileged multiarch/qemu-user-static:register
  - |
    for f in /proc/sys/fs/binfmt_misc/*; do \
      if [ "${f##*/}" != "register" ]; then \
        echo "#### $f ####"; cat "$f"; echo; \
      fi; \
    done

# vim:set et ts=2 sw=2:
