language: bash
sudo: required
services: docker

branches:
  only:
  - master

addons:
  apt:
    packages:
    - binfmt-support
    - qemu-user-static

script:
  - docker build -t vicamo/binfmt-qemu:lastest .
  - ls -al /proc/sys/fs/binfmt_misc
  - docker run --rm --privileged vicamo/binfmt-qemu:latest
  - |
    for f in /proc/sys/fs/binfmt_misc/*; do \
      if [ "${f##*/}" != "register" ]; then \
        echo "#### $f ####"; cat "$f"; echo; \
      fi; \
    done

after_script:
  - docker images

# vim:set et ts=2 sw=2:
