language: bash

branches:
  only:
  - native

addons:
  apt:
    packages:
    - binfmt-support
    - qemu-user-static

script:
  - |
    for f in /proc/sys/fs/binfmt_misc/*; do \
      if [ "${f##*/}" != "status" ]; then \
        echo "#### $f ####"; cat "$f"; echo; \
      fi; \
    done

# vim:set et ts=2 sw=2:
