language: bash
dist: xenial
sudo: required
services: docker

env:
  global:
  - secure: "VwPavJERimyhuMJgB3G2BJ/HcsYWsFhI7OXJSU5hxio9+c0An1fjamiA7SCikdHa3DwBBs52jLyfTf4KSWac1ZlDEigL+Fe3/HIcS5+RbDBQGrtl45d60XlXHltPAj362s/iTjs1zowZ772uFAeYNod31NuuFs/OMyZDzFwrfCYwe406tlmttZ4cXgphW8sko6pDEzmCwgeomoCtF9UxiRJTvKHN/ApFU6gf3b0FHac4MIYx/FlG08PTLApvx8rsJiaP9LuS2b8NEaDGOxu9h1x/WJkHlaBjenrMkc8cYPHc1chS3zYjUUhEA4Ozbm5LJvTzjAdq9zHn2aJKA/ZgFCAad2W8jZnjG3NNJe5yxhVXf8LVPwTnku0eBD++hVUtk1MNqdSPuhuxrV0qjyZ402iEJGGYkxHoyYteyGKafI71QbMiIICnXNlYuA/CEDzs7jvvMnebh057Rt7gxl6HKO8BcrCJxpVDcDFJN72sAVqdoSpFz0Da/i+ENoHAffbjJ6Ht2m3ORuG12tnHpXp6T880Nzr+P21xBGyK31VjeDOfsBSe1HSmd9zCjCZCGJIHtbLD8C2M+mRhic3GJgf+St018bpBkGV4yrBzHgJuM3/QKMSTKrLU7mqDCfY0AN12QeemcSNczSjx1adhXspbY0p8x3aYflcpKZbxGhUDRSQ="
  matrix:
  - DIST=debian SUITE=bullseye
  - DIST=debian SUITE=buster
  - DIST=debian SUITE=jessie
  - DIST=debian SUITE=sid
  - DIST=debian SUITE=stretch
  - DIST=ubuntu SUITE=bionic ALIAS=latest
  - DIST=ubuntu SUITE=eoan ALIAS=rolling
  - DIST=ubuntu SUITE=focal ALIAS=devel
  - DIST=ubuntu SUITE=trusty
  - DIST=ubuntu SUITE=xenial

branches:
  only:
  - master

script:
  - docker build -t ${DOCKER_USER}/binfmt-qemu:$SUITE $DIST/$SUITE
  - if [ $DIST = "debian" ]; then
      RELEASE_URL=https://deb.debian.org/debian/dists/${SUITE}/Release;
      ALIAS=$(wget --quiet -O - ${RELEASE_URL} | grep ^Suite | cut -d ' ' -f2);
    fi;
    if [ -n "$ALIAS" ]; then
      docker tag ${DOCKER_USER}/binfmt-qemu:$SUITE ${DOCKER_USER}/binfmt-qemu:$ALIAS;
    fi;
    docker images;
  - ls -al /proc/sys/fs/binfmt_misc
  - docker run --rm --privileged ${DOCKER_USER}/binfmt-qemu:$SUITE
  - sudo update-binfmts --display

after_script:
- if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
    docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}";
    for image in $(docker images | grep ^${DOCKER_USER}/binfmt-qemu | awk '{print $1 ":" $2}'); do
      docker push $image;
    done
  fi

notifications:
  slack:
    secure: "AOdflQScD4Kq+7QMyMzNSSmmQIysmLYv2qgfKu8uQdlCv9kD0doJBWcE7yj5S7+Lg4rv6uZOmpknJt7HcvtfIYqiQ3xsbJ9vMSq2H0HdjLszkIpnjoxH39+qMdN1I2Z43jl8KKpbzYSEB1+77GF1/2gD/HR0909T6Kye6WQlQLOnqIwyFkHy+1XIaC/6Ha6UUXJszcw5TOY6ovcX+VT5A77SCvIc5st8U+4BI+4kg712GFXNv+iNdjGCwCnOXlAeAwvBXGu6HFNB0xhUIcWLSLdpbT1QHj8BUWEQITnw7n1gjXkM+yvbmUZH7OvWj+l1et3peEXt96dbnJFy6/oZygZdDMJn4pCgmgJFjGKzna3AL5LPJT6OMDqBSuY945ESIeX5afo5JvvC6F+veETu67oaA6oRs2a7VhxrxiwGXrzy8dJAvhDsHuIbpl4d9v4OkCOyNTq58Rvfn4x+y7SVl8bfM3VAouxAujj0fjK3CDJPRT+lp5HB/eyMDvAG+kaQAl5t1kwfIT6niE75ljClSOJ/dbTDDc7OwallEU5ZVvPhd1MT6Bg+CDiVYjG1gkU+5gGUEkJ0s/YZi0IqF2ml/HxW2xiao3vATA0LVf7NdMOOTxjbuz6iHPeL8NF+04dAN22aTg5stLf7ml3ZlE9YmvR1lB2z4aSRZAnz//G0rYo="

# vim:set et ts=2 sw=2:
